cd runs
cd ./1 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./2 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./3 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./4 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./5 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./6 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./7 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./8 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./9 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./10 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./11 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./12 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./13 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./14 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./15 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./16 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./17 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./18 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./19 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./20
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./21 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./22 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./23 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./24 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./25 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./26 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./27 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./28 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./29 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./30 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./31 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./32 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./33 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./34 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./35 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./36 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./37 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./38 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./39 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./40
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./41 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./42 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./43 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./44 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./45 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./46 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./47 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./48 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./49 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./50 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./51 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./52 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./53 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./54 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./55 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./56 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./57 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./58 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./59 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./60
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./61 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./62 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./63 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./64 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./65 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./66 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./67 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./68 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./69 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./70 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./71 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./72 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./73 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./74 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./75 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./76 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./77 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./78 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./79 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
 cd ./80
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./81 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./82 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./83 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./84 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./85 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./86 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./87 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./88 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./89 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./90 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./91 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./92 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./93 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./94 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./95 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./96 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./97 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./98 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./99 
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../
cd ./100
 mf2k_h5  6_months_run.mfn 
del  "fort.40"
del "mf2k_h5.exe"
del "6_months_run.asp"
del "6_months_run.ba6"
del "6_months_run.chd"
del "6_months_run.dis"
del "6_months_run.h5"
del "6_months_run.lpf"
del "6_months_run.mfn"
del "6_months_run.oc"
del "6_months_run.out"
del "6_months_run.pcg"
 cd ./../







